---
title: "NosAnalizamos"
author: "Irene Ponce Huerta"
date: "2026-05-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(pacman)
library(dplyr)
library(tidyr)
datos <- read_tsv("~/Desktop/universidad/tratamiento de datos/NosAnalizamos/NosAutoanalizamos2026 - NosAutoanalizamos (1).tsv",skip= 28)
datos <- as.data.frame(datos)

datos <- datos %>% drop_na(Id)

datos <- datos %>% filter(Id != "martsobm")
datos <- datos %>% 
  mutate(across(13:17, ~ ifelse(. == "NC", 3, .))) %>% mutate(across(13:17, ~ as.numeric(.)))

```

#tratamiento de notas

```{r}
notas <- c("ALG", "ANM", "FP", "DCS", "MD")

datos <- datos %>% 
  mutate(across(13:17, ~ ifelse(. == "NC", 3, .))) %>% mutate(across(13:17, ~ as.numeric(.)))

Notas <- datos %>%
  select(Id, all_of(notas))

save(Notas, file = "Notas.Rdata")

```

#estadisticos
```{r}
datos %>% summarise(across(where(is.numeric),
                                 list(
                                   media= ~mean(.x, na.rm=TRUE),
                                   minimo = ~min(.x, na.rm=TRUE),
                                   per_25 = ~quantile(.x,0.25, na.rm= TRUE),
                                   maximo = ~max(.x, na.rm= TRUE),
                                   per_75 = ~quantile(.x, 0.75, na.rm= TRUE),
                                   desv= ~sd(.x,na.rm=TRUE),
                                   mediana= ~median(.x, na.rm=TRUE)
                                 ))) 
```

#representacion

```{r}

library(GGally)
ggpairs(datos %>% select(where(is.numeric)))
```

#Correlaciones y covarianzas

```{r}
datos_completos <- datos %>% drop_na(where(is.numeric))

cor_pearson <- cor(datos_completos %>% dplyr::select(where(is.numeric)), method= "pearson")

cor_spearman <-cor(datos_completos %>% dplyr::select(where(is.numeric)), method= "spearman")

covarianza <- cov(datos_completos %>% dplyr::select(where(is.numeric)))

which(cor_pearson == max(cor_pearson, na.rm = TRUE), arr.ind = TRUE)
```

#boxplot asignaturas

```{r}
datos_completos <- datos %>% drop_na(13:17)
datos_completos <- datos_completos %>% pivot_longer(cols= 13:17, names_to= "asignatura", values_to = "calificacion")

datos_completos %>% ggplot(aes(asignaturas,calificaciones, fill= asignaturas)) + geom_boxplot() +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 

```

#ahora segun el sexo
```{r}
datos_completos %>% ggplot(aes(asignaturas,calificaciones, fill= Sex)) +  geom_boxplot() +  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

#ahora con lineas
```{r}
#datos_filtrados <- datos_completos %>%
  group_by(Id) %>% 
  filter(n() == n_distinct(asignaturas)) %>% 
  ungroup() #los que tienen todas las notas

#eso es opcional pq ya sabiamos que son los que no tenian na

datos_filtrados %>% 
  ggplot(aes(x = Id, 
             y = calificaciones, 
             colour = asignaturas, 
             group = asignaturas)) +
  geom_line() +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
